### ISSUE TITLE
Bg picker doesn't work for default image

### ISSUE THREAD

**Issue by tanelj** [Voog/design-amsterdam#34]
[edicy-tools.tpl](https://github.com/Voog/design-amsterdam/blob/99492191d84d2e3d0b9998ac0863c247afe3a168/components/edicy-tools.tpl) needs some refactor.

* [ ] You get JS error when trying to set color for default bg image

```
SecurityError: The operation is insecure.
/javascripts/application.min.js
Line 4
```

* [x] You get JS error on save when you change color opacity for for default bg image

```
ReferenceError: headerBgCombinedLightness is not defined
commitData.combinedLightness = headerBgCombinedLightness;
```

* [x] Lightness calculation should be optimized (cache) - it calculates lightness for every step of opacity. Browser hangs when moving opacity slider ant the image is quite big ~900kb)

* [x] Move general JS code from `edicy-tools` component to JS file.

**Comment by kaspar-naaber** [comment]
I couldn't reproduce the first two issues ("You get JS error when trying to set color for default bg image" and "You get JS error on save when you change color opacity for for default bg image").

But I refactored a lot of code while fixing the other issues. Can you recheck if these issues are still open?

**Comment by kaspar-naaber** [comment]
Couldn't reproduce the error "SecurityError: The operation is insecure." but I refactored the Bg-Picker and the other errors don't occur anymore. @tanelj - pleas check if the first issue is also fixed.

**Comment by tanelj** [comment]
Yes, it's fixed.
