### ISSUE TITLE
Add design editor support

### ISSUE THREAD

**Issue by hennrunnel** [Voog/design-amsterdam#67]

**Comment by SSirjes** [comment]
* [ ]  **HEADER - Title**
If I increase title font, then in mobile overlaps it into mobile menu
![screen shot 2016-05-05 at 15 21 30](https://cloud.githubusercontent.com/assets/13623224/15043506/405ce188-12d6-11e6-9219-e746086abdde.png)

* [ ] **Transparent color makes text invisible.** Should it go under overall designeditor issues? Happens also in other designs
Video: http://recordit.co/9q7TpjtFvy

**Comment by SSirjes** [comment]
_**II round testing (9.05.16)**_

 * [ ] **Form text color differeces in edit and preview mode. Also label text dissapear**
Video: http://recordit.co/Z6KvCXaDUI
