### ISSUE TITLE
Mobile menu layout is not supporting multiline language menu.

### ISSUE THREAD

**Issue by kaspar-naaber** [Voog/design-amsterdam#69]
Language menu items hide main menu if a lot of languages are listed:

With flags.
![screenshot 2016-05-25 11 53 07](https://cloud.githubusercontent.com/assets/3191867/15533926/48aa497c-226f-11e6-9662-55ed5027d4c4.png)

Without flags.
![screenshot 2016-05-25 11 53 37](https://cloud.githubusercontent.com/assets/3191867/15533938/5427f8c6-226f-11e6-9986-b06bc7cf286c.png)

@runnel – design advice needed! :)

**Comment by runnel** [comment]
Is it an actual case or just theoretical?

**Comment by kaspar-naaber** [comment]
At the moment it is theroetical so actually there's no need to fix it yet. :)

**Comment by kaspar-naaber** [comment]
Closing the issue because it is too edge case and no site with this issue hasn't reported yet.
